---
# tasks file for sample-apache
- dnf:
    name:
      - httpd
      - mod_ssl
      - php
- firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
- firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
- firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled
- firewalld:
    port: 443/tcp
    permanent: true
    immediate: true
    state: enabled
- template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd
