---
- hosts: all
  tasks:
  - sysctl:
      name: vm.swappiness
      value: '10'
      state: present
    when: ansible_memtotal_mb | int > 2048
  - debug:
      msg: server memory less than 2048mb
    when: ansible_memtotal_mb | int < 2048

